#!/bin/bash

args=("$@")

script_name=$(basename $0)
script_full_path=$(dirname $(readlink -f $0))

temp_file=$(mktemp /tmp/${script_name}.XXXXXXX)
last_cmd=$?
if [[ ${last_cmd} -ne 0 ]]; then
	echo "Failed to create a temp file for envs"
	exit 1
fi

node ${script_full_path}/index.js ${temp_file}
last_cmd=$?
if [  ${last_cmd} -ne 0 ]; then
    echo "Error: wrapper script returned with non-zero status code: ${last_cmd}"
    exit $last_cmd
fi

# source env vars
. ${temp_file}

# check if secrets sets AWS_LAMBDA_EXEC_WRAPPER 
layer_name=$(basename ${AWS_LAMBDA_EXEC_WRAPPER})
if [[ "${layer_name}" == "${script_name}" ]]; then
    unset AWS_LAMBDA_EXEC_WRAPPER
else
    args=("${AWS_LAMBDA_EXEC_WRAPPER}" "${args[@]}")
fi

rm ${temp_file} > /dev/null 2>&1

# execute the next step
exec ${args[@]}